// Code generated by "enumer -type=DeleteMode -trimprefix=DeleteMode -transform=snake"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _DeleteModeName = "cascadereassign"

var _DeleteModeIndex = [...]uint8{0, 7, 15}

const _DeleteModeLowerName = "cascadereassign"

func (i DeleteMode) String() string {
	i -= 1
	if i >= DeleteMode(len(_DeleteModeIndex)-1) {
		return fmt.Sprintf("DeleteMode(%d)", i+1)
	}
	return _DeleteModeName[_DeleteModeIndex[i]:_DeleteModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DeleteModeNoOp() {
	var x [1]struct{}
	_ = x[DeleteModeCascade-(1)]
	_ = x[DeleteModeReassign-(2)]
}

var _DeleteModeValues = []DeleteMode{DeleteModeCascade, DeleteModeReassign}

var _DeleteModeNameToValueMap = map[string]DeleteMode{
	_DeleteModeName[0:7]:       DeleteModeCascade,
	_DeleteModeLowerName[0:7]:  DeleteModeCascade,
	_DeleteModeName[7:15]:      DeleteModeReassign,
	_DeleteModeLowerName[7:15]: DeleteModeReassign,
}

var _DeleteModeNames = []string{
	_DeleteModeName[0:7],
	_DeleteModeName[7:15],
}

// DeleteModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DeleteModeString(s string) (DeleteMode, error) {
	if val, ok := _DeleteModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DeleteModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DeleteMode values", s)
}

// DeleteModeValues returns all values of the enum
func DeleteModeValues() []DeleteMode {
	return _DeleteModeValues
}

// DeleteModeStrings returns a slice of all String values of the enum
func DeleteModeStrings() []string {
	strs := make([]string, len(_DeleteModeNames))
	copy(strs, _DeleteModeNames)
	return strs
}

// IsADeleteMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DeleteMode) IsADeleteMode() bool {
	for _, v := range _DeleteModeValues {
		if i == v {
			return true
		}
	}
	return false
}
