// Code generated by "stringer -type DeleteMode"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeleteModeUndefined-0]
	_ = x[DeleteModeCascade-1]
	_ = x[DeleteModeReassign-2]
}

const _DeleteMode_name = "DeleteModeUndefinedDeleteModeCascadeDeleteModeReassign"

var _DeleteMode_index = [...]uint8{0, 19, 36, 54}

func (i DeleteMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeleteMode_index)-1 {
		return "DeleteMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeleteMode_name[_DeleteMode_index[idx]:_DeleteMode_index[idx+1]]
}
