// Code generated by "stringer -type SortBy"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SortByID-0]
	_ = x[SortByName-1]
	_ = x[SortByCreatedAt-2]
}

const _SortBy_name = "SortByIDSortByNameSortByCreatedAt"

var _SortBy_index = [...]uint8{0, 8, 18, 33}

func (i SortBy) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SortBy_index)-1 {
		return "SortBy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortBy_name[_SortBy_index[idx]:_SortBy_index[idx+1]]
}
