// Code generated by "enumer -type=SortBy -trimprefix=SortBy -transform=snake"; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _SortByName = "idnamecreated_at"

var _SortByIndex = [...]uint8{0, 2, 6, 16}

const _SortByLowerName = "idnamecreated_at"

func (i SortBy) String() string {
	if i >= SortBy(len(_SortByIndex)-1) {
		return fmt.Sprintf("SortBy(%d)", i)
	}
	return _SortByName[_SortByIndex[i]:_SortByIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SortByNoOp() {
	var x [1]struct{}
	_ = x[SortByID-(0)]
	_ = x[SortByName-(1)]
	_ = x[SortByCreatedAt-(2)]
}

var _SortByValues = []SortBy{SortByID, SortByName, SortByCreatedAt}

var _SortByNameToValueMap = map[string]SortBy{
	_SortByName[0:2]:       SortByID,
	_SortByLowerName[0:2]:  SortByID,
	_SortByName[2:6]:       SortByName,
	_SortByLowerName[2:6]:  SortByName,
	_SortByName[6:16]:      SortByCreatedAt,
	_SortByLowerName[6:16]: SortByCreatedAt,
}

var _SortByNames = []string{
	_SortByName[0:2],
	_SortByName[2:6],
	_SortByName[6:16],
}

// SortByString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SortByString(s string) (SortBy, error) {
	if val, ok := _SortByNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SortByNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SortBy values", s)
}

// SortByValues returns all values of the enum
func SortByValues() []SortBy {
	return _SortByValues
}

// SortByStrings returns a slice of all String values of the enum
func SortByStrings() []string {
	strs := make([]string, len(_SortByNames))
	copy(strs, _SortByNames)
	return strs
}

// IsASortBy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SortBy) IsASortBy() bool {
	for _, v := range _SortByValues {
		if i == v {
			return true
		}
	}
	return false
}
